### ISSUE TITLE
Add Routing Settings

### ISSUE THREAD

**Issue by AbadanVpn** [LorenEteval/Furious#1]
Thank you for publishing this very useful software
Please, if it is possible for you to add Routing Settings like Nekoray and V2rayN software, it would be great
thank you

**Comment by LorenEteval** [comment]
Thanks for the report. I hardly use this setting in v2rayN so I don't even know. But considering some users may need it, I'll take a look at it.

**Comment by AbadanVpn** [comment]
In Iran, due to the blocking of social networks and sites, we are forced to always use VPN, and due to the widespread use of V2RAY services, we have a strong need for these settings so that we can use internal sites directly. There is no need to turn the VPN off and on every time
You can take a look at this library
https://github.com/bootmortis/iran-hosted-domains

Thank you

**Comment by LorenEteval** [comment]
Ah, I see what it means. Is it okay to predefine this routing rule inside the app and provide another routing option called, for example, `Bypass Iran`, just like the existing predefined `Bypass Mainland China`?

**Comment by AbadanVpn** [comment]
Yes, this can be good too But considering that this library is updated every time, I think your time is wasted to update
But if you can put an option that can be edited by the user like other software, it will be really great

**Comment by saminxx** [comment]
if you could plz add a vpn future like nekoray that tunnel whole system

**Comment by LorenEteval** [comment]
> if you could plz add a vpn future like nekoray that tunnel whole system

Hi. At first it was in my plan, but somehow postponed it due to 3rd-party dependency issue and OS root permission consideration. I'll try add this feature soon.

**Comment by LorenEteval** [comment]
> Yes, this can be good too But considering that this library is updated every time, I think your time is wasted to update But if you can put an option that can be edited by the user like other software, it will be really great

Full support for customizing routing rules is supported in [release 0.1.11](https://github.com/LorenEteval/Furious/releases/tag/0.1.11). A built-in routing rule `Bypass Iran` is also added for convenience. Please let me know if there are errors/bugs in this release.

**Comment by LorenEteval** [comment]
Closed as completed.
