### ISSUE TITLE
Support for subscription links

### ISSUE THREAD

**Issue by nimbold** [LorenEteval/Furious#10]
Hello!
I checked every setting possible, but I couldn't find a subscription link service. Is it currently not supported?
Sure, I can copy paste my configs, but the subscription feature + update is so neat.

I also wanted to point out the lack of speed/connectivity test but I saw a similar suggestion, so that's done.

**Comment by LorenEteval** [comment]
Hi. Currently I have no time for this, including any other new feature (just really lack of time). Imagine you need to not only handle UI, internal logic, but also those go repositories to generate corresponding Python binding.

Right now I'm working on Python binding for hysteria2. It will then be integrated into Furious at version 0.2.6, including any other potentially fixes. After that Furious will go into bug-fix mode until the end of this year. So, as I mentioned in previous release, Furious 0.2.6 will be the last release this year.

I hope Furious will support subscription link next year early. That's all the plan I can give.

**Comment by BLOSEregedit** [comment]
项目界面非常简洁清晰，正是我想要的那种软件。如果能更快的支持订阅就更棒了

**Comment by LorenEteval** [comment]
Closed as completed in release [0.2.7](https://github.com/LorenEteval/Furious/releases/tag/0.2.7).
