### ISSUE TITLE
使用hysteria2的时候，无法绕过大陆ip

### ISSUE THREAD

**Issue by jackiehejian** [LorenEteval/Furious#104]
目前使用版本为0.4.7，hysteria2能够正常启动，但是始终全局代理，即便选择绕过大陆ip，依然是全局代理。
请问是否有办法做路由规则来分流，以实现绕过大陆ip

**Comment by LorenEteval** [comment]
见 #39 目前暂不知如何从客户端分流

**Comment by jackiehejian** [comment]
感谢哈
















在 2024-10-08 10:13:31，"Loren Eteval" ***@***.***> 写道：

见 #39 目前暂不知如何从客户端分流
