### ISSUE TITLE
v0.4.8 has Xray-core v1.8.24 instead of v24.9.30

### ISSUE THREAD

**Issue by vint2k** [LorenEteval/Furious#108]
Hello.
Changelog [v0.4.8](https://github.com/LorenEteval/Furious/releases/tag/0.4.8) said that Xray-core updated up to v24.9.30, but in logs we can see:
> [INFO] Xray-core 1.8.24 started

**Comment by LorenEteval** [comment]
This is v24.9.30 indeed. I specified it as v1.8.24 because if I specify v24.9.30 and upload to pypi, subsequent v1.x uploads will no longer be possible (the version number in the pypi package must be incremented)

**Comment by vint2k** [comment]
Sorry, yes, in Core Log:
> [Warning] core: Xray 24.9.30 started
but in Furious Log:
> [Furious.QtFramework.CoreProcess] [INFO] Xray-core 1.8.24 started
