### ISSUE TITLE
Skip PROXY_SERVER_BYPASS action for MacOS and Linux

### ISSUE THREAD

**Issue by vint2k** [LorenEteval/Furious#112]
It looks like that [this action](https://github.com/LorenEteval/Furious/blob/081054e9c0cb358f1469c96b4b0039f50ecc089a/Furious/TrayActions/Connect.py#L267) is not needed for MacOS and Linux, because [PROXY_SERVER_BYPASS](https://github.com/LorenEteval/Furious/blob/081054e9c0cb358f1469c96b4b0039f50ecc089a/Furious/Utility/Constants.py#L61) has valid syntax only for Windows.

Can we skip this action for MacOS and Linux?

**Comment by LorenEteval** [comment]
The `;` delimeter is handled in each platform.

https://github.com/LorenEteval/Furious/blob/081054e9c0cb358f1469c96b4b0039f50ecc089a/Furious/Utility/SystemProxy.py#L157

https://github.com/LorenEteval/Furious/blob/081054e9c0cb358f1469c96b4b0039f50ecc089a/Furious/Utility/SystemProxy.py#L171

Will the `,` delimeter in the new bypass work? Plus is there any reason to use different bypass in each platform.

**Comment by vint2k** [comment]
You need separate multiple items with commas, otherwise it won't work on MacOS.
https://support.apple.com/en-ge/guide/mac-help/mchlp2591/mac

I didn't find any official specifications of `no_proxy` variable for Linux, but in examples says that:
> no_proxy is a comma- or space-separated list of machine or domain names ...
https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

The reason of using different vars in each platform:
MacOS use asteriscs (`*`) for matching subdomains, but Linux for matching use a dot `(.)`
```
*.google.com for MacOS
.google.com for Linux
```
and if you need to build with the same bypass rules for each platform you need to use different vars.

I fixed `bypass.split` args for the platforms.

**Comment by LorenEteval** [comment]
The bypass value here is just used to bypass local domain and ip address. I don't think this fix anything so I'll close this.
