### ISSUE TITLE
0.4.8 版本 MacOS-v12.7.1  安装11.0安装不了，安装10.9后显示已损坏

### ISSUE THREAD

**Issue by lichen1116** [LorenEteval/Furious#126]
11.0不能安装，有一个禁止的符号在图标上，拖不到application里。

10.9能安装，打开时候提示：“ “Furious-GUI”已损坏，无法打开。 您应该将它移到废纸篓。”

忘能修复，谢谢作者，辛苦了！

**Comment by LorenEteval** [comment]
https://github.com/LorenEteval/Furious/discussions/118#discussion-7410222
