### ISSUE TITLE
Important core file is unknown

### ISSUE THREAD

**Issue by jhalx09** [LorenEteval/Furious#129]
哥 linux import xray ，还有 tunsocks hysteria这几个关键文件位置放哪？环境变量里面有它也不调用哇？版本号return 0.0.0了都
![截图 2024-12-04 22-03-15](https://github.com/user-attachments/assets/12fe7996-6517-4775-a1b8-5bb558b91ec4)

**Comment by LorenEteval** [comment]
在Linux中core需要另外pip安装
