### ISSUE TITLE
macOS 13 support

### ISSUE THREAD

**Issue by talentlessguy** [LorenEteval/Furious#130]
Currently if you try to run Furious-GUI on macOS 13, it shows this
<img width="562" alt="Screenshot 2024-12-08 at 14 05 57" src="https://github.com/user-attachments/assets/f0716e95-1764-4c08-a4cd-507b501b5842">

I'm on MacOS 13.4, Darwin v22.5

**Comment by LorenEteval** [comment]
https://github.com/LorenEteval/Furious/discussions/118#discussion-7410222

**Comment by talentlessguy** [comment]
can't it be fixed upstream instead of having to run CLI commands?
