### ISSUE TITLE
Win7 Support?

### ISSUE THREAD

**Issue by alidxdydz** [LorenEteval/Furious#15]
I just tried the client on both Win7 and Win10.
It runs smoothly on Win10. However, it throws the following error on Win7 on startup:

`The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.`

I must mention the latest Python version that supports Win7 is v3.8.x. Therefore, I was wondering if you can support Win7 or not.

**Comment by alidxdydz** [comment]
I must add after downloading `api-ms-win-core-path-l1-1-0.dll` and adding it to `System32` and `SysWOW64`, it returns the following error:

`The application was unable to start correctly (0xc00007b). Click OK to close the application.`

**Comment by LorenEteval** [comment]
> I just tried the client on both Win7 and Win10. It runs smoothly on Win10. However, it throws the following error on Win7 on startup:
> 
> `The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.`
> 
> I must mention the latest Python version that supports Win7 is v3.8.x. Therefore, I was wondering if you can support Win7 or not.

Hi. I'll consider support it. That could take me some time to setup a virtual Win7 environment. However, I doubt that if Qt6/PySide6 can run on Win7.

**Comment by alidxdydz** [comment]
I really don't understand much about these compatibility issues, however, I must mention nekoray client also has stopped supporting Win7 and its latest version for Win7 is v3.17.

Therefore, I must point out 2 things:

1. Since v3.4 there were two releases for Windows separating Win7 and following explanation:
`"原来的 Qt 5.15 包重命名为 windows7-x64 ，兼容较旧系统。请注意：此包随时可能被移除。"
"The original Qt 5.15 package was renamed windows7-x64 to be compatible with older systems. Please note: this package may be removed at any time."`

2. There was this explanation on their telegram channel after removing Win7 support:
`"随着 Go 1.21 的到来，Windows 7~8.1 的支持已正式结束。Windows 7 最后可用的是 3.17 版。"
"With the arrival of Go 1.21, support for Windows 7~8.1 has officially ended. The last version of Windows 7 available was version 3.17."`

I would really appreciate supporting Win7, but I really don't want to waste your time. Since based on your speculation (Qt6/PySide6 on Win7), I assume it won't be possible to support Win7

**Comment by alidxdydz** [comment]
I really don't understand much about these compatibility issues, however, I must mention nekoray client also has stopped supporting Win7 and its latest version for Win7 is v3.17.

Therefore, I must point out 2 things:

1. Since v3.4 there were two releases for Windows separating Win7 and following explanation:
`"原来的 Qt 5.15 包重命名为 windows7-x64 ，兼容较旧系统。请注意：此包随时可能被移除。"`
`"The original Qt 5.15 package was renamed windows7-x64 to be compatible with older systems. Please note: this package may be removed at any time."`

2. There was this explanation on their telegram channel after removing Win7 support:
`"随着 Go 1.21 的到来，Windows 7~8.1 的支持已正式结束。Windows 7 最后可用的是 3.17 版。"`
`"With the arrival of Go 1.21, support for Windows 7~8.1 has officially ended. The last version of Windows 7 available was version 3.17."`

I would really appreciate supporting Win7, but I really don't want to waste your time. Since based on your speculation (Qt6/PySide6 on Win7), I assume it won't be possible to support Win7.

**Comment by LorenEteval** [comment]
> I really don't understand much about these compatibility issues, however, I must mention nekoray client also has stopped supporting Win7 and its latest version for Win7 is v3.17.
> 
> Therefore, I must point out 2 things:
> 
> 1. Since v3.4 there were two releases for Windows separating Win7 and following explanation:
>    `"原来的 Qt 5.15 包重命名为 windows7-x64 ，兼容较旧系统。请注意：此包随时可能被移除。"`
>    `"The original Qt 5.15 package was renamed windows7-x64 to be compatible with older systems. Please note: this package may be removed at any time."`
> 2. There was this explanation on their telegram channel after removing Win7 support:
>    `"随着 Go 1.21 的到来，Windows 7~8.1 的支持已正式结束。Windows 7 最后可用的是 3.17 版。"`
>    `"With the arrival of Go 1.21, support for Windows 7~8.1 has officially ended. The last version of Windows 7 available was version 3.17."`
> 
> I would really appreciate supporting Win7, but I really don't want to waste your time. Since based on your speculation (Qt6/PySide6 on Win7), I assume it won't be possible to support Win7.

Just tested on my Win7 VM that PySide 6.1.3 is the last version that can originally run on Win7. However, the bad news is PySide 6.1.3 has some key difference in API with PySide 6.5 that Furious is currently depending on. So Win7 support must be done in a new branch, and requires a lot of work to refactor the code.

Also notice that PySide 6.5 is currently the [newest LTS support version](https://endoflife.date/qt) by Qt, and PySide 6.1.x will not receive any updates or bug fixes.

Win7 support should be feasible based on PySide 6.1.3. I may add it in my spare time, but in a low priority.

**Comment by alidxdydz** [comment]
Thank you for your consideration.

**Comment by LorenEteval** [comment]
Closed as completed in [release 0.2.11](https://github.com/LorenEteval/Furious/releases/tag/0.2.11)

**Comment by alidxdydz** [comment]
Thank you very much for adding Win7 support.
