### ISSUE TITLE
Trying to add Hysteria2 Server Config

### ISSUE THREAD

**Issue by teamcoltra** [LorenEteval/Furious#17]
I can't find anything in the wiki or anywhere in Furious documentation on how to actually add a Hysteria2 Server Config. On my server (successfully running Hysteria2) I don't see a way to generate a Share Link or JSON configuration. So I thought I would manually add my servers IP address and such but I have to still create a JSON file it seems but I don't know the template it needs.

**Comment by LorenEteval** [comment]
> I can't find anything in the wiki or anywhere in Furious documentation on how to actually add a Hysteria2 Server Config. On my server (successfully running Hysteria2) I don't see a way to generate a Share Link or JSON configuration. So I thought I would manually add my servers IP address and such but I have to still create a JSON file it seems but I don't know the template it needs.

Please refer to hysteria official document [here](https://hysteria.network/docs/misc/Hate-YAML/). It provides a template json and explains how to convert from `yaml` to `json` if you already have a yaml configuration.

**Comment by danialza** [comment]
> > I can't find anything in the wiki or anywhere in Furious documentation on how to actually add a Hysteria2 Server Config. On my server (successfully running Hysteria2) I don't see a way to generate a Share Link or JSON configuration. So I thought I would manually add my servers IP address and such but I have to still create a JSON file it seems but I don't know the template it needs.
> 
> Please refer to hysteria official document [here](https://hysteria.network/docs/misc/Hate-YAML/). It provides a template json and explains how to convert from `yaml` to `json` if you already have a yaml configuration.

Dear @LorenEteval could you please help on the JSON sample? in hysteria i could'nt find one complete simple with all inbound and outbound and all settings.

**Comment by LorenEteval** [comment]
> > > I can't find anything in the wiki or anywhere in Furious documentation on how to actually add a Hysteria2 Server Config. On my server (successfully running Hysteria2) I don't see a way to generate a Share Link or JSON configuration. So I thought I would manually add my servers IP address and such but I have to still create a JSON file it seems but I don't know the template it needs.
> > 
> > 
> > Please refer to hysteria official document [here](https://hysteria.network/docs/misc/Hate-YAML/). It provides a template json and explains how to convert from `yaml` to `json` if you already have a yaml configuration.
> 
> Dear @LorenEteval could you please help on the JSON sample? in hysteria i could'nt find one complete sample with all inbound and outbound and all settings.

The link I posted already has a JSON sample that you need. If you just install hy2 from scratch on your server, then you need to figure out those fields manually to be able to use it on the client side, which is not recommended unless you are experienced user. 

Instead most of the one-click/automatic installation script will let you customize installation, and generates share link/JSON config/YAML config for you.
