### ISSUE TITLE
mac使用问题，添加好配置，但是报错：Furious在您的服务器配置中找不到任何有效的http代理端点。

### ISSUE THREAD

**Issue by robertlv226** [LorenEteval/Furious#18]
mac下面报错： Furious在您的服务器配置中找不到任何有效的http代理端点。
我添加的是 hy2节点，已经导入成功，ping测试和下行测试都ok的，但是连接就报上面的错误

**Comment by LorenEteval** [comment]
> mac下面报错： Furious在您的服务器配置中找不到任何有效的http代理端点。 我添加的是 hy2节点，已经导入成功，ping测试和下行测试都ok的，但是连接就报上面的错误

加入
```json
"http": {
    "listen": "127.0.0.1:10809"
},
```
