### ISSUE TITLE
routing not working

### ISSUE THREAD

**Issue by farhadsaberi** [LorenEteval/Furious#19]
Hi, 
Bypass Iran doesn't work. 
Mac 14.0, used the latest version.

**Comment by LorenEteval** [comment]
> Hi, Bypass Iran doesn't work. Mac 14.0, used the latest version.

I just checked the implementation. This should not be a bug on Furious side.

Notice that currently Hy2 does not support routing on the client side. If you are using Xray-core and `Bypass Iran` still fails to work, please try downloading the newest `iran.dat` from [here](https://github.com/bootmortis/iran-hosted-domains/releases) and import it via `Settings` -> `Routing Settings...` -> `Edit Xray-core Routing Rules`(which replaces the old `iran.dat`), and then reconnect.

You can also download and specify `hysteria_client.acl` if you are using Hy1.
