### ISSUE TITLE
Download and upload speed

### ISSUE THREAD

**Issue by paolosezart** [LorenEteval/Furious#2]
Are there any plans to add tests to this program to determine the download and upload speed?

**Comment by paolosezart** [comment]
Perhaps I expressed myself incorrectly. I meant checking ALL servers for speed, for example through the service http://cachefly.cachefly.net/100mb.test . For example in the v2rayN program it looks like this:

![Speed test](https://github.com/LorenEteval/Furious/assets/38177890/567498ed-cf24-4c90-a269-89157eab021b)

**Comment by LorenEteval** [comment]
Hi. Currently I have no plan for this, but thanks for pointing that out.

**Comment by LorenEteval** [comment]
Closed as completed in release [0.2.7](https://github.com/LorenEteval/Furious/releases/tag/0.2.7).
