### ISSUE TITLE
Invalid share link. The content of the clipboard is error to adding hysteria2

### ISSUE THREAD

**Issue by shahryarjb** [LorenEteval/Furious#23]
Hello, it is a hysteria2 link that I want to add (I changed the ip and my password)
```
hysteria2://00000000@111.111.141.11:443/?insecure=1&obfs=salamander&obfs-password=00000000&sni=google.com#HysteriaV2 IPv4
```
When I want to add it, I get `Invalid share link. The content of the clipboard` error in `macOS 13.4`

I installed `Furious-0.2.9-macOS-11.0-x86_64.dmg`
Thanks

**Comment by LorenEteval** [comment]
Currently Furious does not support hy2 share link. You can instead import via JSON configuration.

**Comment by shahryarjb** [comment]
@LorenEteval  Thanks, do you have any sample how to add `hy2` as a JSON config?

**Comment by LorenEteval** [comment]
> @LorenEteval Thanks, do you have any sample how to add `hy2` as a JSON config? Could you add this option please?

I assume most of the one-click/automatic installation script will generate both share link, YAML config and JSON config for the users.

Given your share link, this is a JSON sample:

```json
{
    "server": "ADDRESS:PORT",
    "auth": "MY_AUTH_DATA_00000000",
    "tls": {
        "sni": "google.com",
        "insecure": true
    },
    "obfs": {
        "type": "salamander",
        "salamander": {
            "password": "MY_OBFS_PASSWORD_00000000"
        }
    },
    "socks5": {
        "listen": "127.0.0.1:10808"
    },
    "http": {
        "listen": "127.0.0.1:10809"
    },
    "transport": {
        "udp": {
            "hopInterval": "30s"
        }
    }
}
```

Replace `server`, `auth` and `password` field with your own data. It should be enough to run. You can test download speed in Furious to see if the configuration is indeed working.

**Comment by shahryarjb** [comment]
@LorenEteval Sorry again.

Based on my link
```
hysteria2://AUTH@ADDRESS:PORT/?insecure=1&obfs=salamander&obfs-password=PASSWORD&sni=google.com#HysteriaV2 IPv4
```

and the config you gave me
```json
{
    "server": "ADDRESS:PORT",
    "auth": "AUTH",
    "tls": {
        "sni": "google.com",
        "insecure": true
    },
    "obfs": {
        "type": "salamander",
        "salamander": {
            "password": "PASSWORD"
        }
    },
    "socks5": {
        "listen": "127.0.0.1:10808"
    },
    "http": {
        "listen": "127.0.0.1:10809"
    },
    "transport": {
        "type": "udp",
        "udp": {
            "hopInterval": "30s"
        }
    }
}
```
Note: based on `https://v2.hysteria.network/docs/advanced/Full-Client-Config/` docs I add type to `transport`, but it can not connect I cant see any error

![Screenshot 2023-10-15 at 17 47 02](https://github.com/LorenEteval/Furious/assets/8413604/48586c86-f052-4237-ac65-a053147eb995)



Thank you in advance

**Comment by LorenEteval** [comment]
> @LorenEteval Sorry again.
> 
> Based on my link
> 
> ```
> hysteria2://AUTH@ADDRESS:PORT/?insecure=1&obfs=salamander&obfs-password=PASSWORD&sni=google.com#HysteriaV2 IPv4
> ```
> 
> and the config you gave me
> 
> ```json
> {
>     "server": "ADDRESS:PORT",
>     "auth": "AUTH",
>     "tls": {
>         "sni": "google.com",
>         "insecure": true
>     },
>     "obfs": {
>         "type": "salamander",
>         "salamander": {
>             "password": "PASSWORD"
>         }
>     },
>     "socks5": {
>         "listen": "127.0.0.1:10808"
>     },
>     "http": {
>         "listen": "127.0.0.1:10809"
>     },
>     "transport": {
>         "type": "udp",
>         "udp": {
>             "hopInterval": "30s"
>         }
>     }
> }
> ```
> 
> Note: based on `https://v2.hysteria.network/docs/advanced/Full-Client-Config/` docs I add type to `transport`, but it can not connect I cant see any error
> 
> ![Screenshot 2023-10-15 at 17 47 02](https://user-images.githubusercontent.com/8413604/275331481-48586c86-f052-4237-ac65-a053147eb995.png)
> 
> Thank you in advance

Never mind. There still may be problem with this config because in your share link I didn't see port hopping enabled. The `transport` field is just copied from my personal config. So deleting the `transport` field should work.

```json
{
    "server": "ADDRESS:PORT",
    "auth": "AUTH",
    "tls": {
        "sni": "google.com",
        "insecure": true
    },
    "obfs": {
        "type": "salamander",
        "salamander": {
            "password": "PASSWORD"
        }
    },
    "socks5": {
        "listen": "127.0.0.1:10808"
    },
    "http": {
        "listen": "127.0.0.1:10809"
    },
}
```

**Comment by shahryarjb** [comment]
Thanks
@LorenEteval , unfortunately still does not work, my friends uses this on shadow rocket app and works or `v2ray` client in android, but inside macOS (intel type) there is no app let me use `hy2`

The link I have is something like this, it is on 443 from server
```
hysteria2://2222222@185.222.178.33:443 
```

I check my mac and there is not app which is enabled on  `10809` port
By the way, always on 40% to connect, it is going to show the disconnected process

Thank you

**Comment by LorenEteval** [comment]
That's wired. I'm pretty sure I didn't miss any values in your share link.

What's the disconnect reason that Furious gave? You can check and paste the core log(if any) and Furious application log when you perform connect action. They are in `Help` menu.

**Comment by shahryarjb** [comment]
@LorenEteval Hello again, in macOS we have no help menu for Furious GUI.

![Screenshot 2023-10-15 at 20 52 22](https://github.com/LorenEteval/Furious/assets/8413604/b8b2b28e-db27-4d50-a715-6cc522f9798a)

I got this error as notif in macOS

![Screenshot 2023-10-15 at 20 55 26](https://github.com/LorenEteval/Furious/assets/8413604/d06180a0-d96c-44f9-a8d8-cc6a88b30180)

Yes I saved every changes.

**Comment by alidxdydz** [comment]
> Thanks
> @LorenEteval , unfortunately still does not work, my friends uses this on shadow rocket app and works or `v2ray` client in android, but inside macOS (intel type) there is no app let me use `hy2`
> 
> The link I have is something like this, it is on 443 from server
> ```
> hysteria2://2222222@185.222.178.33:443 
> ```
> 
> I check my mac and there is not app which is enabled on  `10809` port
> By the way, always on 40% to connect, it is going to show the disconnected process
> 
> Thank you

I haven't tested hy2. However, since you mentioned phone client, I suggest importing hy2 to nekobox client using your share link. Then, extract hy2 config into json format. Only copy the hy2 outbound to Furious.
It will most likely work, since original hy2 and sing-box hy2 almost use same options.

**Comment by LorenEteval** [comment]
> > Thanks
> > @LorenEteval , unfortunately still does not work, my friends uses this on shadow rocket app and works or `v2ray` client in android, but inside macOS (intel type) there is no app let me use `hy2`
> > The link I have is something like this, it is on 443 from server
> > ```
> > hysteria2://2222222@185.222.178.33:443 
> > ```
> > 
> > 
> > I check my mac and there is not app which is enabled on  `10809` port
> > By the way, always on 40% to connect, it is going to show the disconnected process
> > Thank you
> 
> I haven't tested hy2. However, since you mentioned phone client, I suggest importing hy2 to nekobox client using your share link. Then, extract hy2 config into json format. Only copy the hy2 outbound to Furious. It will most likely work, since original hy2 and sing-box hy2 almost use same options.
> 
> Update: I may have mistaken and msybe the json files are not compatible. I got these from nekobox (sing-box core).
> 
> Outbound URI:
> 
> ```
> hysteria2://AuthenticationPayload@1.2.3.4:1234/?insecure=1&sni=www.google.com&obfs=salamander&obfs-password=ObfuscationPassword#Hy2-Out
> ```
> 
> Outbound JSON:
> 
> ```
> {
>   "outbounds": [
>     {
>       "tag": "Hy2-Out",
>       "type": "hysteria2",
>       "domain_strategy": "",
>       "server": "1.2.3.4",
>       "server_port": 1234,
>       "obfs": {
>         "password": "ObfuscationPassword",
>         "type": "salamander"
>       },
>       "password": "AuthenticationPayload",
>       "tls": {
>         "enabled": true,
>         "server_name": "www.google.com",
>         "insecure": true,
>         "alpn": [
>           "h3"
>         ]
>       },
>       "up_mbps": 10,
>       "down_mbps": 50
>     }
>   ]
> }
> ```
> 
> As you can see, in json config of sing-box hy2, you should even specify upload and download speed limit.

Thank you. I think this issue is resolved by your reply. I'll close this.

By the way, refactoring code to support win7 is much easier than I thought, so win7(x86_64) support will come at next release, just in days.
