### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by zhouxinghong** [LorenEteval/Furious#25]
### Icon colors need improvement:
Hello!
I found a problem that can be improved, that is, when the user turns on the VPN mode, please change the color of the system tray icon to green. This will make it very convenient to know what network mode you are currently using to access the Internet.
Windows 10
The latest version

**Comment by zhouxinghong** [comment]
The second UI theme needs improvement:
The current UI theme only has Light color but no Dark color. Even if the operating system is set to Dark color, Furious UI is still Light color. Like this:
![image](https://github.com/LorenEteval/Furious/assets/54253524/4650d8f1-c6a2-41e8-8a3e-49baac76f952)
![image](https://github.com/LorenEteval/Furious/assets/54253524/995e6b2c-5695-4d7c-90ac-cf791fab1ad5)

Windows 10
0.2.11 Preview

**Comment by LorenEteval** [comment]
> when the user turns on the VPN mode, please change the color of the system tray icon to green.

It will be added in 0.2.12.

> The current UI theme only has Light color but no Dark color. Even if the operating system is set to Dark color, Furious UI is still Light color. Like this:

Currently this is not feasible via the programmer side (Qt will change this if possible, e.g. on macOS and Linux). Furious takes care of changing the menu icons to black/white accordingly.

**Comment by LorenEteval** [comment]
Closed as completed in [release 0.2.12](https://github.com/LorenEteval/Furious/releases/tag/0.2.12)
