### ISSUE TITLE
Could not find a version that satisfies the requirement PySide6-Essentials

### ISSUE THREAD

**Issue by torajghaffari** [LorenEteval/Furious#3]
![image](https://github.com/LorenEteval/Furious/assets/62768434/27ccf904-19da-4c13-9d30-6bb103db9791)

**Comment by LorenEteval** [comment]
Please provide your Python version, Linux distribution version via `cat /etc/lsb-release` and glibc version via `ldd --version`

**Comment by LorenEteval** [comment]
Closed as lack of information.
