### ISSUE TITLE
ERROR: No matching distribution found for PySide6-Essentials (from Furious-GUI)

### ISSUE THREAD

**Issue by jetsonwork** [LorenEteval/Furious#32]
Hello

in linux:

ERROR: Could not find a version that satisfies the requirement PySide6-Essentials (from Furious-GUI) (from versions: none)
ERROR: No matching distribution found for PySide6-Essentials (from Furious-GUI)

python -V
Python 3.8.16

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"

ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by LorenEteval** [comment]
I've noticed that Furious has a really bad support on Linux based on `pip`.

I've just changed requirement `PySide6-Essentials` to `PySide6` in the newest `0.2.11.2` version. Can you try again? Thank you.

**Comment by jetsonwork** [comment]
sudo pip install Furious-GUI


Collecting Furious-GUI
  Downloading Furious_GUI-0.2.11.2-py3-none-any.whl (7.1 MB)
     |████████████████████████████████| 7.1 MB 146 kB/s 
Collecting tun2socks>2.5.1
  Using cached tun2socks-2.5.1.2.tar.gz (588 kB)
Collecting PySide6
  Downloading PySide6-6.2.4-6.2.4-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (268.2 MB)
     |████████████████████████████████| 268.2 MB 4.0 kB/s 
Collecting ping3
  Using cached ping3-4.0.4-py3-none-any.whl (13 kB)
Collecting pyqrcode
  Using cached PyQRCode-1.2.1.tar.gz (36 kB)
Collecting darkdetect; sys_platform != "darwin"
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting ujson
  Using cached ujson-5.8.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)
Collecting pybase64
  Using cached pybase64-1.3.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (65 kB)
Collecting Xray-core
  Using cached Xray-core-1.8.4.1.tar.gz (825 kB)
Collecting pypng
  Using cached pypng-0.20220715.0-py3-none-any.whl (58 kB)
Collecting shiboken6==6.2.4
  Downloading shiboken6-6.2.4-6.2.4-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 11.1 MB/s 
Building wheels for collected packages: tun2socks, pyqrcode, Xray-core
  Building wheel for tun2socks (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4gfuun3/tun2socks/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4gfuun3/tun2socks/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ktnh3lk7
       cwd: /tmp/pip-install-c4gfuun3/tun2socks/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/tun2socks
  copying tun2socks/__init__.py -> build/lib/tun2socks
  running egg_info
  writing tun2socks.egg-info/PKG-INFO
  writing dependency_links to tun2socks.egg-info/dependency_links.txt
  writing top-level names to tun2socks.egg-info/top_level.txt
  reading manifest file 'tun2socks.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'tun2socks.*' under directory 'tun2socks'
  writing manifest file 'tun2socks.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  error: [Errno 2] No such file or directory: 'go'
  ----------------------------------------
  ERROR: Failed building wheel for tun2socks
  Running setup.py clean for tun2socks
  Building wheel for pyqrcode (setup.py) ... done
  Created wheel for pyqrcode: filename=PyQRCode-1.2.1-py3-none-any.whl size=36245 sha256=38a5ea8ad8edf6adba2fa9a7088540ea8c8eed631e47613369d9474f5c1a28e4
  Stored in directory: /root/.cache/pip/wheels/e1/1a/48/c9d6b7295d3750a8d38001a2a3e86d8816e2e90964a0cc73cd
  Building wheel for Xray-core (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4gfuun3/Xray-core/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4gfuun3/Xray-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dm_zapo1
       cwd: /tmp/pip-install-c4gfuun3/Xray-core/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/xray
  copying xray/__init__.py -> build/lib/xray
  running egg_info
  writing Xray_core.egg-info/PKG-INFO
  writing dependency_links to Xray_core.egg-info/dependency_links.txt
  writing top-level names to Xray_core.egg-info/top_level.txt
  reading manifest file 'Xray_core.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'xray.*' under directory 'xray'
  writing manifest file 'Xray_core.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  error: [Errno 2] No such file or directory: 'go'
  ----------------------------------------
  ERROR: Failed building wheel for Xray-core
  Running setup.py clean for Xray-core
Successfully built pyqrcode
Failed to build tun2socks Xray-core
Installing collected packages: tun2socks, shiboken6, PySide6, ping3, pyqrcode, darkdetect, ujson, pybase64, Xray-core, pypng, Furious-GUI
    Running setup.py install for tun2socks ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4gfuun3/tun2socks/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4gfuun3/tun2socks/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g5bkml3a/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/tun2socks
         cwd: /tmp/pip-install-c4gfuun3/tun2socks/
    Complete output (2 lines):
    running install
    error: [Errno 2] No such file or directory: 'go'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4gfuun3/tun2socks/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4gfuun3/tun2socks/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g5bkml3a/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/tun2socks Check the logs for full command output.

**Comment by LorenEteval** [comment]
[Core Building Tools](https://github.com/LorenEteval/Furious#core-building-tools)

**Comment by jetsonwork** [comment]
go version
go version go1.20.10 linux/amd64


sudo pip install Furious-GUI
Collecting Furious-GUI
  Using cached Furious_GUI-0.2.11.2-py3-none-any.whl (7.1 MB)
Collecting tun2socks>2.5.1
  Using cached tun2socks-2.5.1.2.tar.gz (588 kB)
Collecting pypng
  Using cached pypng-0.20220715.0-py3-none-any.whl (58 kB)
Collecting PySide6
  Using cached PySide6-6.2.4-6.2.4-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (268.2 MB)
Collecting ping3
  Using cached ping3-4.0.4-py3-none-any.whl (13 kB)
Collecting darkdetect; sys_platform != "darwin"
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Processing /root/.cache/pip/wheels/e1/1a/48/c9d6b7295d3750a8d38001a2a3e86d8816e2e90964a0cc73cd/PyQRCode-1.2.1-py3-none-any.whl
Collecting Xray-core
  Using cached Xray-core-1.8.4.1.tar.gz (825 kB)
Collecting ujson
  Using cached ujson-5.8.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)
Collecting pybase64
  Using cached pybase64-1.3.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (65 kB)
Collecting shiboken6==6.2.4
  Using cached shiboken6-6.2.4-6.2.4-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (1.0 MB)
Building wheels for collected packages: tun2socks, Xray-core
  Building wheel for tun2socks (setup.py) ... done
  Created wheel for tun2socks: filename=tun2socks-2.5.1.2-py3-none-any.whl size=3720510 sha256=4fdeb4fc1809c476f9e093663c2cb5c86cecb2444870fec77fe5bd97e860f94a
  Stored in directory: /root/.cache/pip/wheels/68/af/e7/7231f4b410065e8cd380a61750c3e42100c9be08d3c1aed8e2
  Building wheel for Xray-core (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xgqkvkaf/Xray-core/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xgqkvkaf/Xray-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-retucnyq
       cwd: /tmp/pip-install-xgqkvkaf/Xray-core/
  Complete output (87 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/xray
  copying xray/__init__.py -> build/lib/xray
  running egg_info
  writing Xray_core.egg-info/PKG-INFO
  writing dependency_links to Xray_core.egg-info/dependency_links.txt
  writing top-level names to Xray_core.egg-info/top_level.txt
  reading manifest file 'Xray_core.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'xray.*' under directory 'xray'
  writing manifest file 'Xray_core.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  go: downloading google.golang.org/protobuf v1.31.0
  go: downloading google.golang.org/grpc v1.57.0
  go: downloading golang.org/x/sys v0.11.0
  go: downloading github.com/pires/go-proxyproto v0.7.0
  go: downloading github.com/sagernet/sing v0.2.9
  go: downloading github.com/sagernet/sing-shadowsocks v0.2.4
  go: downloading github.com/ghodss/yaml v1.0.1-0.20220118164431-d8423dcdf344
  go: downloading github.com/pelletier/go-toml v1.9.5
  go: downloading github.com/quic-go/quic-go v0.38.1
  go: downloading golang.org/x/net v0.14.0
  go: downloading go4.org/netipx v0.0.0-20230824141953-6213f710f925
  go: downloading golang.org/x/crypto v0.12.0
  go: downloading github.com/refraction-networking/utls v1.4.3
  go: downloading github.com/sagernet/wireguard-go v0.0.0-20221116151939-c99467f53f2c
  go: downloading gvisor.dev/gvisor v0.0.0-20230822212503-5bf4e5f98744
  go: downloading github.com/xtls/reality v0.0.0-20230828171259-e426190d57f6
  go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20230822172742-b8732ec3820d
  go: downloading lukechampine.com/blake3 v1.2.1
  go: downloading gopkg.in/yaml.v2 v2.4.0
  go: downloading github.com/seiflotfy/cuckoofilter v0.0.0-20220411075957-e3b120b3f5fb
  go: downloading github.com/v2fly/ss-bloomring v0.0.0-20210312155135-28617310f63e
  go: downloading github.com/andybalholm/brotli v1.0.5
  go: downloading github.com/gaukas/godicttls v0.0.4
  go: downloading github.com/klauspost/compress v1.16.7
  go: downloading github.com/golang/protobuf v1.5.3
  go: downloading github.com/francoispqt/gojay v1.2.13
  go: downloading golang.org/x/exp v0.0.0-20230725093048-515e97ebf090
  go: downloading github.com/klauspost/cpuid/v2 v2.2.5
  go: downloading golang.org/x/text v0.12.0
  go: downloading github.com/dgryski/go-metro v0.0.0-20211217172704-adc40b04c140
  go: downloading github.com/riobard/go-bloom v0.0.0-20200614022211-cdc8013cb5b3
  go: downloading github.com/quic-go/qtls-go1-20 v0.3.3
  /root/go/pkg/mod/github.com/refraction-networking/utls@v1.4.3/u_handshake_client.go:16:2: github.com/klauspost/compress@v1.16.7: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.16.7.zip: 403 Forbidden
  proxy/wireguard/tun.go:17:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:18:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:19:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:20:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:21:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:22:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:23:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:24:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:25:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  proxy/wireguard/tun.go:26:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 82, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 72, in run
      buildXrayCore()
    File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 27, in buildXrayCore
      runCommand(
    File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 21, in runCommand
      subprocess.run(command, check=True)
    File "/usr/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['go', 'build', '-C', 'xray-go', '-o', '/tmp/pip-install-xgqkvkaf/Xray-core/gobuild/xray.a', '-buildmode=c-archive', '-trimpath', '-ldflags', '-s -w -buildid=', './main']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for Xray-core
  Running setup.py clean for Xray-core
Successfully built tun2socks
Failed to build Xray-core
Installing collected packages: tun2socks, pypng, shiboken6, PySide6, ping3, darkdetect, pyqrcode, Xray-core, ujson, pybase64, Furious-GUI
    Running setup.py install for Xray-core ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xgqkvkaf/Xray-core/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xgqkvkaf/Xray-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7setpjqw/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/Xray-core
         cwd: /tmp/pip-install-xgqkvkaf/Xray-core/
    Complete output (35 lines):
    running install
    go: downloading gvisor.dev/gvisor v0.0.0-20230822212503-5bf4e5f98744
    go: downloading github.com/klauspost/compress v1.16.7
    /root/go/pkg/mod/github.com/refraction-networking/utls@v1.4.3/u_handshake_client.go:16:2: github.com/klauspost/compress@v1.16.7: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.16.7.zip: 403 Forbidden
    proxy/wireguard/tun.go:17:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:18:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:19:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:20:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:21:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:22:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:23:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:24:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:25:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:26:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 82, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 72, in run
        buildXrayCore()
      File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 27, in buildXrayCore
        runCommand(
      File "/tmp/pip-install-xgqkvkaf/Xray-core/setup.py", line 21, in runCommand
        subprocess.run(command, check=True)
      File "/usr/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['go', 'build', '-C', 'xray-go', '-o', '/tmp/pip-install-xgqkvkaf/Xray-core/gobuild/xray.a', '-buildmode=c-archive', '-trimpath', '-ldflags', '-s -w -buildid=', './main']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xgqkvkaf/Xray-core/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xgqkvkaf/Xray-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7setpjqw/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/Xray-core Check the logs for full command output.

**Comment by LorenEteval** [comment]
```
    proxy/wireguard/tun.go:17:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:18:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:19:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:20:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:21:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:22:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:23:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:24:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:25:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
    proxy/wireguard/tun.go:26:2: gvisor.dev/gvisor@v0.0.0-20230822212503-5bf4e5f98744: reading https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20230822212503-5bf4e5f98744.zip: 403 Forbidden
```

I believe the error is quite clear and is not on the application side.
