### ISSUE TITLE
user defined routings can't be saved 

### ISSUE THREAD

**Issue by petermaple** [LorenEteval/Furious#33]
after restart of the app, the user defined routing will be lost and not be saved.

**Comment by LorenEteval** [comment]
Confirmed, thanks. I'm currently too busy to fix it. A temporary solution would be just copy & paste RoutingObject in the user configuration.

**Comment by LorenEteval** [comment]
Fixed in [release 0.2.12](https://github.com/LorenEteval/Furious/releases/tag/0.2.12)
