### ISSUE TITLE
Significant performace issue | Battery drain

### ISSUE THREAD

**Issue by lilendian0x00** [LorenEteval/Furious#35]
Hello and thanks for your 🌟 and useful program! 😄

I've been using your program since version **0.2.9** on macOS (TUN mode) and I've noticed a significant performance issue in the newer versions.

Due to the battery drain caused by the newer versions, I had to roll back to version **0.2.9** (https://github.com/LorenEteval/Furious/releases/download/0.2.9/Furious-0.2.9-macOS-12.0_arm64.dmg).

**Comment by lilendian0x00** [comment]
Your welcome. 

I used htop to analyze the CPU usage of both higher versions and that version, and the difference isn't just about 20-30%. It's actually about 100% or so.

**Comment by LorenEteval** [comment]
I'll try to fix that in next release.

**Comment by lilendian0x00** [comment]
Appreciate it so much.

**Comment by LorenEteval** [comment]
It should be fixed in [release 0.2.12](https://github.com/LorenEteval/Furious/releases/tag/0.2.12). Please check if the issue still exists.

**Comment by lilendian0x00** [comment]
WoW, appreciate it dude! I've tested it and it even has much better performance in compare to the version 0.2.9!

Plus many new improvements...
