### ISSUE TITLE
1个问题反馈，功能建议

### ISSUE THREAD

**Issue by DLGum** [LorenEteval/Furious#36]
问题：hysteria端口跳跃功能未支持
从分享链接导入hysteria线路后，配置文件内并无端口跳跃相关项

功能建议：双击选择到无效线路，连接会断开。希望自动切回原线路保持连接。

**Comment by LorenEteval** [comment]
> 问题：hysteria端口跳跃功能未支持
从分享链接导入hysteria线路后，配置文件内并无端口跳跃相关项

端口跳跃功能应该是支持的。是哪部分配置漏掉了，有一个能复现的例子最好

> 功能建议：双击选择到无效线路，连接会断开。希望自动切回原线路保持连接。

内部暂时没有检测无效线路的逻辑（以前有，但是去掉了），现在的行为就是直接切换

**Comment by DLGum** [comment]
> > 问题：hysteria端口跳跃功能未支持
> > 从分享链接导入hysteria线路后，配置文件内并无端口跳跃相关项
> 
> 端口跳跃功能应该是支持的。是哪部分配置漏掉了，有一个能复现的例子最好
> 
> > 功能建议：双击选择到无效线路，连接会断开。希望自动切回原线路保持连接。
> 
> 内部暂时没有检测无效线路的逻辑（以前有，但是去掉了），现在的行为就是直接切换

应该支持，在编辑器简单改改配置加入端口跳跃可以运行。但是我不清楚是否正确运行。
我的改法是
原来
"server": "地址:端口",
改为
"server": "地址:端口,起-末",

应该是识别分享链接漏了一部分
线路分享链接的格式（服务端生成或者从nekobox导出都是这个格式）：
hy2://密码@域名:默认端口/?mport=默认端口%2C起-末&sni=域名#备注名

这个格式的分享链接在Furious导入后，右侧配置窗口内是看不到跳跃端口相关部分的。

**Comment by LorenEteval** [comment]
> hy2://密码@域名:默认端口/?mport=默认端口%2C起-末&sni=域名#备注名

`mport`参数在hy2官方文档里没有，可能是实现上有差异，hy2官方的share link将动态端口放在server里：`hy2://密码@域名:默认端口,起-末...`，Furious也是按照这个导入/导出的，所以才会有动态端口参数丢失的问题。

> 目前启动线路是不是只能在托盘右键菜单，如果断开就要跑过去重连。挺郁闷

是的，后面优化一下。最近比较忙，一些feature只有后面再加
