### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by DLGum** [LorenEteval/Furious#37]
性能开销极高
在高速下载时他能数着秒让我的笔记本电脑风扇起飞
并且这个下载是大陆内的下载并不需要代理

**Comment by LorenEteval** [comment]
> 性能开销极高 在高速下载时他能数着秒让我的笔记本电脑风扇起飞 并且这个下载是大陆内的下载并不需要代理

是哪个平台？原因应该和 #35 一样，CPU占用资源偏高。可能在笔记本电脑上由于资源有限，这个问题比较明显。

可以试一下0.2.9的版本有没有这个问题。我这边只能优化一下发布一个`0.2.12`的pre-release版本

**Comment by DLGum** [comment]
AMD 6800H平台win10，下载工具是迅雷（下载电影不用走代理），线路是reality线路。。只要迅雷在下载，然后开着Furious代理挂在后台，复现率基本百分百。此时Furious的cpu占用率在9%左右。

**Comment by DLGum** [comment]
> > 性能开销极高 在高速下载时他能数着秒让我的笔记本电脑风扇起飞 并且这个下载是大陆内的下载并不需要代理
> 
> 是哪个平台？原因应该和 #35 一样，CPU占用资源偏高。可能在笔记本电脑上由于资源有限，这个问题比较明显。
> 
> 可以试一下0.2.9的版本有没有这个问题。我这边只能优化一下发布一个`0.2.12`的pre-release版本

AMD 6800H平台win10，下载工具是迅雷（下载电影不用走代理），线路是reality线路。。只要迅雷在下载，然后开着Furious代理挂在后台，复现率基本百分百。此时Furious的cpu占用率在9%左右。

**Comment by LorenEteval** [comment]
感谢反馈。我调一下内部timer的阈值

**Comment by LorenEteval** [comment]
[0.2.12](https://github.com/LorenEteval/Furious/releases/tag/0.2.12) 应该修复了这个问题
