### ISSUE TITLE
Can I use this on Ubuntu 18.04?

### ISSUE THREAD

**Issue by Ru1yi** [LorenEteval/Furious#38]
I see this only support 20.04 and 22.04. Can I use Fusious on 18.04?

**Comment by LorenEteval** [comment]
> I see this only support 20.04 and 22.04. Can I use Fusious on 18.04?

Yes. Linux version is only available via `pip` currently.

**Comment by Ru1yi** [comment]
> > I see this only support 20.04 and 22.04. Can I use Fusious on 18.04?
> 
> Yes. Linux version is only available via `pip` currently.

Thanks for reply.
