### ISSUE TITLE
绕过大陆ip未生效

### ISSUE THREAD

**Issue by Van426326** [LorenEteval/Furious#39]
Hysteria2协议  AMD MacOs环境下 绕过大陆ip未生效
![image](https://github.com/LorenEteval/Furious/assets/33017677/48c46031-4bac-4df3-a345-09cc5e660555)
![image](https://github.com/LorenEteval/Furious/assets/33017677/d933196f-b42a-4231-ae99-27fe4f1680e0)

**Comment by LorenEteval** [comment]
hy2不支持客户端路由。hy2下所有`绕过xxx`行为与`全球`行为一致
