### ISSUE TITLE
功能好用就是用得不习惯，可能要求有点无理，希望能得到大佬的回复。

### ISSUE THREAD

**Issue by mydracula** [LorenEteval/Furious#41]
能不能把【上移 下移 克隆 删除】这一区域的功能给删除，上移下移在右键有这个功能，而且这个功能用的也少，就算用一般都是移到第一个，希望可以通过拖拉拽移动才方便。 删除可以用键盘的delete按键更方便，克隆也没有ctrl +C 或者 +V方便，这个 复制粘贴是ctrl+shift+c或者v ，复制粘贴还有个弹框还要手动点，很麻烦

把【上移 下移 克隆 删除】删除后，把系统托管图标右键部分设置放上来，比如路由、连接、，，因为连接有个通知，还会挡住了，要点个设置需要点好几下，这个通知也很碍眼，把进度条关了的情况下通知确实有必要，这个通知最好几百ms差不多了，挡住太久了

编辑器，不是每个人都要编辑器的，可以设置不显示，设置不显示后那编辑功能是不是没用了，可以放在系统托管图标右键设置，编辑的功能 ctrl +C  或者 +V为什么不能复制节点，还要全选为什么不能全选节点。隐藏编辑器的时候，点右下角的编辑配置没反应，编辑有点多余，显示才能去编辑对吧

这个表格不能自适应缩小就有横向滚动条，不能设置哪些需要哪些列表不需要，展示的表头太多了，我直接导入节点没有订阅，需要有这一列吗，希望我可以自己选择展示哪些表头，竖向滚动条样式不太行，太挡视线了

然后这个编辑配置希望是v2rayn 和 nekoray那种编辑 直接双击当前项然后编辑，而不是编辑json配置，这个json配置说实话用的很少 

![image](https://github.com/LorenEteval/Furious/assets/71320199/fafaad22-c066-499a-9f8d-efca262c2efc)
![image](https://github.com/LorenEteval/Furious/assets/71320199/de0fc857-4cf8-4ed7-a572-3b922b544b95)

**Comment by LorenEteval** [comment]
口水话太多。列出关键点比较好

CTRL+SHIFT+C 变成 CTRL+C，什么几百ms等等就不考虑了，没有意义。

你说的一些功能都有，什么delete删除，全选节点等。

双击编辑0.3支持。
