### ISSUE TITLE
mac端的配置文件在哪个位置，我将Sniffing的Enable的值改为false后无法启动了

### ISSUE THREAD

**Issue by ScienceNoBorders** [LorenEteval/Furious#50]
<img width="398" alt="image" src="https://github.com/LorenEteval/Furious/assets/37797698/b48d11df-3191-4974-8132-cb0417e9bde4">

**Comment by LorenEteval** [comment]
存储的是所有服务器配置的base64，直接修改几乎不可能。你看下app还能启动不，否则可能得重装等
