### ISSUE TITLE
Furious本身可以当http/SOCKS5服务器吗

### ISSUE THREAD

**Issue by MalikWilliams1greher** [LorenEteval/Furious#55]
给局域网的其他设备使用

**Comment by LorenEteval** [comment]
没太明白，Furious本身是一个app，你要建立http/socks服务器得在里面配置成http/socks的出站和入站

**Comment by MalikWilliams1greher** [comment]
<img width="804" alt="image" src="https://github.com/LorenEteval/Furious/assets/147643826/23f5a78a-4ee5-4f04-888a-e17c500e9b94">
类似图上的功能

**Comment by MalikWilliams1greher** [comment]
<img width="937" alt="image" src="https://github.com/LorenEteval/Furious/assets/147643826/69ce0785-d715-41f7-904b-b21aa3697d75">


就是让furious当做一个SOCKS服务器

**Comment by MalikWilliams1greher** [comment]
<img width="755" alt="image" src="https://github.com/LorenEteval/Furious/assets/147643826/2084ca1b-fdb7-4f52-8347-4c0a37b37e1a">
这样的

**Comment by LorenEteval** [comment]
![image](https://github.com/LorenEteval/Furious/assets/139033850/29ef0d37-fda0-498d-a9bb-3be42346552d)

**Comment by MalikWilliams1greher** [comment]
可以做成UI界面操作吗

**Comment by LorenEteval** [comment]
> 可以做成UI界面操作吗

不是不可以，得后面去了，优先级不高。直接通过配置文件改是最快也是最方便的
