### ISSUE TITLE
Updating Geosite and Geoip for Iran

### ISSUE THREAD

**Issue by khashayarxy** [LorenEteval/Furious#59]
Last time I checked the bypass feature on Furious, it didn't work well, and I found the issue.

As I searched through the domains of the current database, it didn't include many addresses and was outdated.

This database is accurate and up-to-date. I've tested it, and it works well.

https://github.com/Chocolate4U/Iran-v2ray-rules

**Comment by LorenEteval** [comment]
Still I don't know if `Bypass Iran` mode originally works. I guess this needs more verification.

**Comment by khashayarxy** [comment]
I just tested the Geoip and Geosite configs from https://github.com/Chocolate4U/Iran-v2ray-rules

The problem is in the original JSON config. I added the JSON config bellow and it works fine.

1. There is no need for `Iran.dat` file. `geoip.dat` and `geosite.dat` are enough.
2. Bypass doesn't work with VPN Mode, only on Proxy Mode.

```
{
  "domainStrategy": "IPIfNonMatch",
  "domainMatcher": "hybrid",
  "rules": [
    {
      "type": "field",
      "domain": [
        "geosite:ir"
      ],
      "outboundTag": "direct"
    },
    {
      "type": "field",
      "ip": [
        "geoip:private",
        "geoip:ir"
      ],
      "outboundTag": "direct"
    },
    {
      "type": "field",
      "port": "0-65535",
      "outboundTag": "proxy"
    }
  ]
}

```

**Comment by khashayarxy** [comment]
This website uses Geo-blocking https://dir.iran.ir

Here's some images before and after using the new config.

![Screenshot 2024-01-14 190704](https://github.com/LorenEteval/Furious/assets/42047526/42f98989-b597-4ddf-b536-ff95c8fe7735)
![Screenshot 2024-01-14 190957](https://github.com/LorenEteval/Furious/assets/42047526/136a8d24-8556-42e4-a59a-06751e0a22dd)

**Comment by LorenEteval** [comment]
> This website uses Geo-blocking https://dir.iran.ir
> 
> Here's some images before and after using the new config.
> 
> ![Screenshot 2024-01-14 190704](https://private-user-images.githubusercontent.com/42047526/296591089-42f98989-b597-4ddf-b536-ff95c8fe7735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTYzMDEsIm5iZiI6MTcwNjA1NjAwMSwicGF0aCI6Ii80MjA0NzUyNi8yOTY1OTEwODktNDJmOTg5ODktYjU5Ny00ZGRmLWI1MzYtZmY5NWM4ZmU3NzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAwMjY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWQ1MGMzNGI0ZTg2NzU1MDk4NDQ4NDdkNGQyNGY3Y2MyZTU5N2NlOTY5Mjc2MjYzNzEyNTE0N2E1MGU3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwBRasoUunHGlHG_x_HwpTcMzemU29fWbSdoAPeIDB0) ![Screenshot 2024-01-14 190957](https://private-user-images.githubusercontent.com/42047526/296591128-136a8d24-8556-42e4-a59a-06751e0a22dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTYzMDEsIm5iZiI6MTcwNjA1NjAwMSwicGF0aCI6Ii80MjA0NzUyNi8yOTY1OTExMjgtMTM2YThkMjQtODU1Ni00MmU0LWE1OWEtMDY3NTFlMGEyMmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAwMjY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYzBkMTRiYzM0OGRmY2MzMDQ0YjY0MmNiN2M0YjUzNGYxOTRjMGI2YmI5NzBkNGJhYzI3OGI1M2EyNmMxMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j8GwH5c5zh7hcKolFRoqOCEWnENFps7_lprq2Yf5I0I)

None of the .ir domain get bypassed or just some succeed in the original config?

**Comment by khashayarxy** [comment]
Thanks for the response.

I would appreciate it if you would try my solution in the app. you just have to change the JSON config and update the databases from the link I sent in the first post.

There is nothing to do on my side because there is no `iran.dat` file in the repository I mentioned. you can still include that but it's from a different repository and is the same as `geoip.dat` as far as I know.

it's okay if you don't want to do it but I thought I should explain. as for PR I'm not an expert in coding and I pasted the codes in previous issues from ChatGPT and thought it could help. as for mentioning other apps I thought it would help you find the solution from other source codes.

Have a nice day :)

**Comment by khashayarxy** [comment]
> None of the .ir domain get bypassed or just some succeed in the original config?

Sorry I didn't see this post in my phone. it was hidden. anyways, as for original config no it wasn't working because even that I updated the databases, it still wouldn't bypass any website (with geo-block). I had a lot of chats with ChatGPT to figure this out.
I tried at least 4-5 different variations of the JSON config and only one of them actually worked.

**Comment by LorenEteval** [comment]
It seems that you didn't get my point. The configuration was not written by me out of thin air. I would expect a "something is wrong" answer rather than "no need" and some other alternatives. This does not help the project at all. 

Also in the release page I've written clearly that `geoip` and `geosite` have already been fetched from other project. I don't see any point to switch to another right now without knowing their difference.

**Comment by LorenEteval** [comment]
> It seems that you didn't get my point. The configuration was not written by me out of thin air. I would expect a "something is wrong" answer rather than "no need" and some other alternatives. This does not help the project at all.
> 
> Also in the release page I've written clearly that `geoip` and `geosite` have already been fetched from other project. I don't see any point to switch to another right now without knowing their difference.

If `Bypass Iran` is confirmed not working and nobody can tell what's wrong, I'll remove this entry in the next release.

**Comment by khashayarxy** [comment]
I understood that and what I can say is that it seems the JSON format you have used won't get recognized by the app.

Are you sure the same format works for China?

You don't have to change databases. the current database would also work fine I guess.

I'm currently using the custom bypass rule and it works fine. why not use my config instead of deleting it completely?

I only deleted ads part which many times doesn't do any good.
