### ISSUE TITLE
在打开网页时断开连接或切换路由，软件意外终止，且在下一次重启系统前无法再次打开

### ISSUE THREAD

**Issue by PantiPenti** [LorenEteval/Furious#60]
如题，设备系统及型号：
<img width="574" alt="截屏2024-01-20 下午10 53 11" src="https://github.com/LorenEteval/Furious/assets/107738678/34920043-4ab1-4156-9e7e-7597a40468b8">

在打开网页时断开连接或切换路由，软件会无响应
<img width="212" alt="截屏2024-01-21 下午8 17 20" src="https://github.com/LorenEteval/Furious/assets/107738678/9d45d2e4-6538-401a-b204-452b52f6339d">

强制退出软件后弹窗显示“Furious意外终止”，
<img width="356" alt="截屏2024-01-21 下午8 17 32" src="https://github.com/LorenEteval/Furious/assets/107738678/8ad9a154-f6b3-46ec-94ea-c4ec7141dfd4">

<img width="247" alt="截屏2024-01-21 下午8 17 43" src="https://github.com/LorenEteval/Furious/assets/107738678/f20eac74-3871-4f10-835a-9461399171a0">

**MacOS崩溃报告见第二条comment。**
在下一次重启系统之前尝试打开软件会在加载几秒后自动退出，使用终端打开提示
<img width="577" alt="截屏2024-01-20 下午10 50 45" src="https://github.com/LorenEteval/Furious/assets/107738678/8e514685-e199-47e4-a7a0-7498feda6714">

直到重启系统后才能再次正常打开软件，正常使用。

**Comment by PantiPenti** [comment]
由于报告过长，请见如下文件
[MacOS崩溃报告.txt](https://github.com/LorenEteval/Furious/files/14001301/MacOS.txt)

**Comment by LorenEteval** [comment]
我抽空复现一下，按理应该不会有这个情况

**Comment by LorenEteval** [comment]
可以试一下0.3.0有没有这个问题，旧版本的问题我这边就不看了

**Comment by PantiPenti** [comment]
最近试过了，在0.3.0该问题依然存在，且多次出现。

**Comment by LorenEteval** [comment]
有一个录屏最好。不知道你说的 打开网页 具体是什么操作
