### ISSUE TITLE
是否可以增加一个“不修改系统代理”的开关？

### ISSUE THREAD

**Issue by lfdisk** [LorenEteval/Furious#62]
因为我仅仅需要让浏览器 (Firefox + SwitchyOmega) 使用代理。
谢谢！

**Comment by LorenEteval** [comment]
> 因为我仅仅需要让浏览器 (Firefox + SwitchyOmega) 使用代理。 谢谢！

#63 

不出意外应该能在下个版本里加入

**Comment by lfdisk** [comment]
期待中。
