### ISSUE TITLE
Furious 0.3.0

### ISSUE THREAD

**Issue by LorenEteval** [LorenEteval/Furious#63]
New version will come out together with `Python 3.11.8` on [2024-02-05](https://peps.python.org/pep-0664/#bugfix-releases)

---

新版本将在 [2024-02-05](https://peps.python.org/pep-0664/#bugfix-releases) 与 `Python 3.11.8` 一起发布

**Comment by greatwudi2022** [comment]
今天发布新版本吗？期待

**Comment by LorenEteval** [comment]
[0.3.0 release](https://github.com/LorenEteval/Furious/releases/tag/0.3.0)
