### ISSUE TITLE
IPv6 address can not exec ping test

### ISSUE THREAD

**Issue by eddiehex** [LorenEteval/Furious#64]
when the target IP type is IPv6 the ping test will show error.

![Snipaste_2024-02-07_19-37-30](https://github.com/LorenEteval/Furious/assets/76837196/2907be93-60e8-4e23-b631-d587888d4ff9)

**Comment by LorenEteval** [comment]
This issue seems to be related to upstream package `ping3`

**Comment by LorenEteval** [comment]
Fixed in [release 0.3.9](https://github.com/LorenEteval/Furious/releases/tag/0.3.9)
