### ISSUE TITLE
VPN mode (TUN) has failed on 0.3.0 version

### ISSUE THREAD

**Issue by lilendian0x00** [LorenEteval/Furious#65]
Hello and thanks for your great work.

As soon as I updated my Furious to version 0.3.0, the VPN Mode (AKA TUN mode) has failed to work properly on MacOS v14.2.1 (Sonoma). Also Routing is set to Global.

To be exact, my traffic won't be forwarded to the destination (e.g. curl stuck giving response).

I also have to mention that it's working perfectly on 0.2.13 version.

**Comment by LorenEteval** [comment]
Hi. 0.3.0 macOS TUN mode is working on my side.

More DNS setup is added in 0.3.0 version to avoid DNS leak. You can inspect them in application logs.

If it still doesn't work please provide me any error logs.

**Comment by LorenEteval** [comment]
Closed as not reproducible
