### ISSUE TITLE
Debug running

### ISSUE THREAD

**Issue by elegance666** [LorenEteval/Furious#7]
Is there anyway to debug why Furious can't run?
I have a fresh windows 10, After installing .Net frame work 7 and Installing Cygwin64 and add path to windows variables, But Furious  still can't run without any error or notification.

**Comment by LorenEteval** [comment]
Hi. First of all, there are two ways of installing Furious on Windows.

* Download zip file in the release page that contains pre-built binaries. In this case there is no dependency required.
* Install Furious via `pip`. In this case you need to have core building tools ready.

Although the pre-built binaries are tagged as `windows-x86_64`, I personally tested on my Windows VM that the binaries can work at specifically Windows version number `20H2` and later.

So to answer your quesion:

* Launch binaries via command line and see if the console gives some error message.
* If the console does give error messages, please check that your Windows version number is at least `20H2` or later(You can check this via Windows `Settings->System->About`).
* Install Windows update to upgrade your Windows version number(You can do this by using Windows built-in upgrade feature in `Settings`), and re-lauch binaries to see if it's running successfully.

**Comment by LorenEteval** [comment]
Closed as lack of respond.
