### ISSUE TITLE
建议支持sing-box内核

### ISSUE THREAD

**Issue by redstoneleo** [LorenEteval/Furious#70]
建议支持[sing-box内核](https://github.com/SagerNet/sing-box)，只要支持了这个就不用再维护[hysteria2-python](https://github.com/LorenEteval/hysteria2-python)和[Xray-core-python](https://github.com/LorenEteval/Xray-core-python)了，此外根据[作者博客](https://sekai.icu/)上面的内容说sing-box是比xray更优秀的实现。

**Comment by LorenEteval** [comment]
可以考虑支持，看今年五六月份有没有空吧
