### ISSUE TITLE
请问路由里的自定义在哪里可以设置？

### ISSUE THREAD

**Issue by keengrass** [LorenEteval/Furious#76]
请问路由里的自定义在哪里可以设置？
另外一直有一个问题，就是点击编辑配置的时候，这个配置窗口始终被挡在最后面（被其它窗口遮挡），无法点击的时候就出现在眼前。

**Comment by LorenEteval** [comment]
自定义路由会使用JSON配置中定义的路由配置，仅适合高级用户

第二个现象我也注意到了，不过在windows下同样的代码没有问题，只能怀疑是Qt的问题或设计如此了
