### ISSUE TITLE
0.4.5 版本打开失败

### ISSUE THREAD

**Issue by dgulan** [LorenEteval/Furious#84]
覆盖安装完成后，打开软件失败，reopen 错误依旧，提示如下图：
<img width="1000" alt="image" src="https://github.com/LorenEteval/Furious/assets/28797169/0fb28c79-5ac1-42d9-9b25-9726d2355b91">

卸载以后，重新安装，仍然失败。
菜鸟不知道原因，请帮忙看看。
谢谢作者。

**Comment by activeliang** [comment]
+1

**Comment by activeliang** [comment]
我的系统版本是12.6，打不开提示损坏，强制打开后，就发上面的截图一下，报错

**Comment by gy8958398** [comment]
+1

**Comment by TanZhiwen2001** [comment]
macOS-10.9版本在macOS14.5下正常打开，但是11版本提示已损坏。

**Comment by LorenEteval** [comment]
是打包工具的问题，可以用`macOS-10.9`的版本，另外今天也会更新一下Core新出一个版本

**Comment by dgulan** [comment]
谢谢，已经解决。
