### ISSUE TITLE
VLESS with XTLS-Reality - Performance Issues

### ISSUE THREAD

**Issue by alexsammers1** [LorenEteval/Furious#87]
Hey Everybody!

Quick check - anybody else noticing any performance issues with VLESS with XTLS-Reality protocol lately? With my internet connection - 500 Mbps upload/download, I had no issues watching Youtube Videos in 4K or higher via Wireguard protocol, but now with Vless the buffering/loading times are crazy. It also seems to be affecting WhatsApp and Telegram apps - constantly disconnecting, fails to download/upload images, etc.. Timeframe wise - this started happening 2 weeks ago and getting worse each day.

e.g. Connection Speed via Sysadmin Tools in a 4K Youtube Video:
- Vless - 3935 Kbps
- No VPN -  251927 Kbps
- Wireguard - 40382 Kbps

Wireguard is great, but it can't differentiate between different locale/region, so if I need to use Russian websites, I have to disable it - with Vless, you can do both, no issues.

I also checked with the server support, no changes or speed limits have been introduced, that might affect the server's performance; ping less than 40 ms to my PC.

3X-UI - v2.3.5, Xray Core - v1.8.16, Windows 11 Client - v0.4.6

**Comment by X-49** [comment]
I don't watch videos in 4K, I prefer 2K resolution, but I checked to see how the situation is for me.

4K video YouTube:
AV1 codec reaches 30000 kbps
VP9 codec reaches 25000 kbps

In general, the videos are comfortable to watch without buffering. And it's worth noting that my vless connection is hosted on free web hosting. The problems are clearly in your server that you pay for.

**Comment by alexsammers1** [comment]
> I don't watch videos in 4K, I prefer 2K resolution, but I checked to see how the situation is for me.
> 
> 4K video YouTube: AV1 codec reaches 30000 kbps VP9 codec reaches 25000 kbps
> 
> In general, the videos are comfortable to watch without buffering. And it's worth noting that my vless connection is hosted on free web hosting. The problems are clearly in your server that you pay for.

Thanks - appreciate you looking into this!

It looks like it is the server, or just the connection in Russia in general. My server is located in Amsterdam - paid/great speeds/no traffic restriction - no issues before, but smth's def changed. Tried masking under domains in the Netherlands/US - no difference, except using google.com is more stable.

In general, Russians are blocking Youtube now, so could be related to this as well.

Either way, will try to find another hosting in Europe, and see how it goes from there.

**Comment by alexsammers1** [comment]
**Update** - looks like it was the server after all. I've switched to another one, with a location closer to my country - issue resolved, 2k/4k videos loading with no delay, minimal ping latency.

**Comment by 0xTheDad** [comment]
@alexsammers1 Hello, please go to your gmail, I wrote to you with my question.
