### ISSUE TITLE
Furious: command not found...

### ISSUE THREAD

**Issue by Jolymmiles** [LorenEteval/Furious#94]
After pip install Furious-GUI this command without errors a get this
![image](https://github.com/user-attachments/assets/dde0eb82-a7cd-4551-af81-8df63ccf4e14)

Fedora 40

**Comment by LorenEteval** [comment]
Use virtual environment (venv).

**Comment by Jolymmiles** [comment]
> Use virtual environment (venv).

how to do that?

**Comment by Jolymmiles** [comment]
i mean i just follow your instruction for PyPi
![Uploading image.png…]()
