### ISSUE TITLE
Customize routing rules in windows version

### ISSUE THREAD

**Issue by robin98** [LorenEteval/Furious#96]
Hello,
I'm using the windows version on my windows 10, I noticed we have 3 options for routing: Bypass china, Global and Custom.
But how can I edit my own routing rules?

**Comment by alexsammers1** [comment]
> Hello, I'm using the windows version on my windows 10, I noticed we have 3 options for routing: Bypass china, Global and Custom. But how can I edit my own routing rules?

For that, you'd need to customize the JSON Configuration File for your connection. It will open an Editor, and there you can add custom rules under "routing": section. Once you're done, make sure to select Custom Routing and reconnect.
![Customize Routing](https://github.com/user-attachments/assets/c0c88f55-c22b-4455-bb06-1a4cd18529fb)

If you're using 3X or X-UI, you can get the Routing Rules from there, and then just add to the JSON Configuration File in Furious.
![x-ui](https://github.com/user-attachments/assets/6b23e459-6145-4ce9-ad4c-8c9fa01d131d)

**Comment by LorenEteval** [comment]
Thanks for the detailed reply! @alexsammers1
